package com.smartflow.yshyerp.crc.mappper;

import com.smartflow.yshyerp.crc.entity.Crc;
import com.smartflow.yshyerp.crc.entity.CrcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author haita
 */
@Repository
@Transactional
public interface CrcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crc
     *
     * @mbggenerated
     */
    int countByExample(CrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crc
     *
     * @mbggenerated
     */
    int deleteByExample(CrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crc
     *
     * @mbggenerated
     */
    int insert(Crc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crc
     *
     * @mbggenerated
     */
    int insertSelective(Crc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crc
     *
     * @mbggenerated
     */
    List<Crc> selectByExample(CrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Crc record, @Param("example") CrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Crc record, @Param("example") CrcExample example);
}