package com.smartflow.yshyerp.crc.mappper;

import com.smartflow.yshyerp.crc.entity.Factory;
import com.smartflow.yshyerp.crc.entity.FactoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Factory
     *
     * @mbggenerated
     */
    int countByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Factory
     *
     * @mbggenerated
     */
    int deleteByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Factory
     *
     * @mbggenerated
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Factory
     *
     * @mbggenerated
     */
    int insertSelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Factory
     *
     * @mbggenerated
     */
    List<Factory> selectByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Factory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Factory record, @Param("example") FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Factory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Factory record, @Param("example") FactoryExample example);
}