mybatis:
  typeAliasesPackage: com.smartflow.yshyerp.crc.entity
  mapperLocations: classpath:mapping/*.xml


spring:
  datasource:
    url: jdbc:sqlserver://192.168.1.252:1433;databaseName=invdbf
    username: sa
    password: 1qaz@wsx
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



server:
  servlet:
    context-path: /demo
  port: 8082