mybatis:
  typeAliasesPackage: com.smartflow.yshyerp.crc.entity
  mapperLocations: classpath:mapping/*.xml


spring:
  datasource:
    url: jdbc:sqlserver://192.168.1.252:1433;databaseName=invdbf
    username: sa
    password: 1qaz@wsx
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  data:
    mongodb:
      database: yshyerp
      host: 192.168.1.221
      password: 1qaz@wsx
      username: root
      port: 27017

  mongodb:
    crcCollection: crcCollection


server:
  servlet:
    context-path: /demo
  port: 8082