package com.smartflow.yshyerp.crc.entity;

import java.io.Serializable;
import java.util.Date;

public class Area implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.AreaNumber
     *
     * @mbggenerated
     */
    private String areanumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.FactoryId
     *
     * @mbggenerated
     */
    private Integer factoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.CreatorId
     *
     * @mbggenerated
     */
    private Integer creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.CreationDateTime
     *
     * @mbggenerated
     */
    private Date creationdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.EditorId
     *
     * @mbggenerated
     */
    private Integer editorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.EditDateTime
     *
     * @mbggenerated
     */
    private Date editdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.AreaType
     *
     * @mbggenerated
     */
    private Integer areatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Area.State
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Area
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.Id
     *
     * @return the value of Area.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.Id
     *
     * @param id the value for Area.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.AreaNumber
     *
     * @return the value of Area.AreaNumber
     *
     * @mbggenerated
     */
    public String getAreanumber() {
        return areanumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.AreaNumber
     *
     * @param areanumber the value for Area.AreaNumber
     *
     * @mbggenerated
     */
    public void setAreanumber(String areanumber) {
        this.areanumber = areanumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.Description
     *
     * @return the value of Area.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.Description
     *
     * @param description the value for Area.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.FactoryId
     *
     * @return the value of Area.FactoryId
     *
     * @mbggenerated
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.FactoryId
     *
     * @param factoryid the value for Area.FactoryId
     *
     * @mbggenerated
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.CreatorId
     *
     * @return the value of Area.CreatorId
     *
     * @mbggenerated
     */
    public Integer getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.CreatorId
     *
     * @param creatorid the value for Area.CreatorId
     *
     * @mbggenerated
     */
    public void setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.CreationDateTime
     *
     * @return the value of Area.CreationDateTime
     *
     * @mbggenerated
     */
    public Date getCreationdatetime() {
        return creationdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.CreationDateTime
     *
     * @param creationdatetime the value for Area.CreationDateTime
     *
     * @mbggenerated
     */
    public void setCreationdatetime(Date creationdatetime) {
        this.creationdatetime = creationdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.EditorId
     *
     * @return the value of Area.EditorId
     *
     * @mbggenerated
     */
    public Integer getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.EditorId
     *
     * @param editorid the value for Area.EditorId
     *
     * @mbggenerated
     */
    public void setEditorid(Integer editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.EditDateTime
     *
     * @return the value of Area.EditDateTime
     *
     * @mbggenerated
     */
    public Date getEditdatetime() {
        return editdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.EditDateTime
     *
     * @param editdatetime the value for Area.EditDateTime
     *
     * @mbggenerated
     */
    public void setEditdatetime(Date editdatetime) {
        this.editdatetime = editdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.Name
     *
     * @return the value of Area.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.Name
     *
     * @param name the value for Area.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.AreaType
     *
     * @return the value of Area.AreaType
     *
     * @mbggenerated
     */
    public Integer getAreatype() {
        return areatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.AreaType
     *
     * @param areatype the value for Area.AreaType
     *
     * @mbggenerated
     */
    public void setAreatype(Integer areatype) {
        this.areatype = areatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Area.State
     *
     * @return the value of Area.State
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Area.State
     *
     * @param state the value for Area.State
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}