package com.smartflow.yshyerp.crc.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Crc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.crc_no
     *
     * @mbggenerated
     */
    private String crcNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.d
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.tank
     *
     * @mbggenerated
     */
    private String tank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.c_customer
     *
     * @mbggenerated
     */
    private String cCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.commodity
     *
     * @mbggenerated
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.tax
     *
     * @mbggenerated
     */
    private Boolean tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.vessel
     *
     * @mbggenerated
     */
    private String vessel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.billid
     *
     * @mbggenerated
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.date1
     *
     * @mbggenerated
     */
    private Date date1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.date2
     *
     * @mbggenerated
     */
    private Date date2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.gauge1
     *
     * @mbggenerated
     */
    private BigDecimal gauge1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.gauge2
     *
     * @mbggenerated
     */
    private BigDecimal gauge2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.temp1
     *
     * @mbggenerated
     */
    private BigDecimal temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.temp2
     *
     * @mbggenerated
     */
    private BigDecimal temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.tsf1
     *
     * @mbggenerated
     */
    private BigDecimal tsf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.tsf2
     *
     * @mbggenerated
     */
    private BigDecimal tsf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.tec1
     *
     * @mbggenerated
     */
    private BigDecimal tec1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.tec2
     *
     * @mbggenerated
     */
    private BigDecimal tec2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.waterdip1
     *
     * @mbggenerated
     */
    private BigDecimal waterdip1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.waterdip2
     *
     * @mbggenerated
     */
    private BigDecimal waterdip2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.dens_obs1
     *
     * @mbggenerated
     */
    private String densObs1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.dens_obs2
     *
     * @mbggenerated
     */
    private String densObs2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.dens_15c1
     *
     * @mbggenerated
     */
    private String dens15c1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.dens_15c2
     *
     * @mbggenerated
     */
    private String dens15c2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.wvolume1
     *
     * @mbggenerated
     */
    private BigDecimal wvolume1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.wvolume2
     *
     * @mbggenerated
     */
    private BigDecimal wvolume2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.volume1
     *
     * @mbggenerated
     */
    private BigDecimal volume1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.volume2
     *
     * @mbggenerated
     */
    private BigDecimal volume2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.vcf1
     *
     * @mbggenerated
     */
    private BigDecimal vcf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.vcf2
     *
     * @mbggenerated
     */
    private BigDecimal vcf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.dcf1
     *
     * @mbggenerated
     */
    private BigDecimal dcf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.dcf2
     *
     * @mbggenerated
     */
    private BigDecimal dcf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.vol15c1
     *
     * @mbggenerated
     */
    private BigDecimal vol15c1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.vol15c2
     *
     * @mbggenerated
     */
    private BigDecimal vol15c2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.wcf1
     *
     * @mbggenerated
     */
    private BigDecimal wcf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.wcf2
     *
     * @mbggenerated
     */
    private BigDecimal wcf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.weight1
     *
     * @mbggenerated
     */
    private BigDecimal weight1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.weight2
     *
     * @mbggenerated
     */
    private BigDecimal weight2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.receive
     *
     * @mbggenerated
     */
    private BigDecimal receive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.slop
     *
     * @mbggenerated
     */
    private BigDecimal slop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.actual
     *
     * @mbggenerated
     */
    private BigDecimal actual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.bill
     *
     * @mbggenerated
     */
    private BigDecimal bill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.out_type
     *
     * @mbggenerated
     */
    private String outType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.t_receive
     *
     * @mbggenerated
     */
    private BigDecimal tReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.variation
     *
     * @mbggenerated
     */
    private BigDecimal variation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.v_percent
     *
     * @mbggenerated
     */
    private BigDecimal vPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.vessel_qty
     *
     * @mbggenerated
     */
    private BigDecimal vesselQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.other_crc_no
     *
     * @mbggenerated
     */
    private String otherCrcNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.gauge_s
     *
     * @mbggenerated
     */
    private String gaugeS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crc.dock
     *
     * @mbggenerated
     */
    private Boolean dock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crc
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.crc_no
     *
     * @return the value of crc.crc_no
     *
     * @mbggenerated
     */
    public String getCrcNo() {
        return crcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.crc_no
     *
     * @param crcNo the value for crc.crc_no
     *
     * @mbggenerated
     */
    public void setCrcNo(String crcNo) {
        this.crcNo = crcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.d
     *
     * @return the value of crc.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.d
     *
     * @param d the value for crc.d
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.tank
     *
     * @return the value of crc.tank
     *
     * @mbggenerated
     */
    public String getTank() {
        return tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.tank
     *
     * @param tank the value for crc.tank
     *
     * @mbggenerated
     */
    public void setTank(String tank) {
        this.tank = tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.c_customer
     *
     * @return the value of crc.c_customer
     *
     * @mbggenerated
     */
    public String getcCustomer() {
        return cCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.c_customer
     *
     * @param cCustomer the value for crc.c_customer
     *
     * @mbggenerated
     */
    public void setcCustomer(String cCustomer) {
        this.cCustomer = cCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.commodity
     *
     * @return the value of crc.commodity
     *
     * @mbggenerated
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.commodity
     *
     * @param commodity the value for crc.commodity
     *
     * @mbggenerated
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.tax
     *
     * @return the value of crc.tax
     *
     * @mbggenerated
     */
    public Boolean getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.tax
     *
     * @param tax the value for crc.tax
     *
     * @mbggenerated
     */
    public void setTax(Boolean tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.vessel
     *
     * @return the value of crc.vessel
     *
     * @mbggenerated
     */
    public String getVessel() {
        return vessel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.vessel
     *
     * @param vessel the value for crc.vessel
     *
     * @mbggenerated
     */
    public void setVessel(String vessel) {
        this.vessel = vessel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.item_no
     *
     * @return the value of crc.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.item_no
     *
     * @param itemNo the value for crc.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.billid
     *
     * @return the value of crc.billid
     *
     * @mbggenerated
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.billid
     *
     * @param billid the value for crc.billid
     *
     * @mbggenerated
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.date1
     *
     * @return the value of crc.date1
     *
     * @mbggenerated
     */
    public Date getDate1() {
        return date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.date1
     *
     * @param date1 the value for crc.date1
     *
     * @mbggenerated
     */
    public void setDate1(Date date1) {
        this.date1 = date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.date2
     *
     * @return the value of crc.date2
     *
     * @mbggenerated
     */
    public Date getDate2() {
        return date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.date2
     *
     * @param date2 the value for crc.date2
     *
     * @mbggenerated
     */
    public void setDate2(Date date2) {
        this.date2 = date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.gauge1
     *
     * @return the value of crc.gauge1
     *
     * @mbggenerated
     */
    public BigDecimal getGauge1() {
        return gauge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.gauge1
     *
     * @param gauge1 the value for crc.gauge1
     *
     * @mbggenerated
     */
    public void setGauge1(BigDecimal gauge1) {
        this.gauge1 = gauge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.gauge2
     *
     * @return the value of crc.gauge2
     *
     * @mbggenerated
     */
    public BigDecimal getGauge2() {
        return gauge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.gauge2
     *
     * @param gauge2 the value for crc.gauge2
     *
     * @mbggenerated
     */
    public void setGauge2(BigDecimal gauge2) {
        this.gauge2 = gauge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.temp1
     *
     * @return the value of crc.temp1
     *
     * @mbggenerated
     */
    public BigDecimal getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.temp1
     *
     * @param temp1 the value for crc.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(BigDecimal temp1) {
        this.temp1 = temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.temp2
     *
     * @return the value of crc.temp2
     *
     * @mbggenerated
     */
    public BigDecimal getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.temp2
     *
     * @param temp2 the value for crc.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(BigDecimal temp2) {
        this.temp2 = temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.tsf1
     *
     * @return the value of crc.tsf1
     *
     * @mbggenerated
     */
    public BigDecimal getTsf1() {
        return tsf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.tsf1
     *
     * @param tsf1 the value for crc.tsf1
     *
     * @mbggenerated
     */
    public void setTsf1(BigDecimal tsf1) {
        this.tsf1 = tsf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.tsf2
     *
     * @return the value of crc.tsf2
     *
     * @mbggenerated
     */
    public BigDecimal getTsf2() {
        return tsf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.tsf2
     *
     * @param tsf2 the value for crc.tsf2
     *
     * @mbggenerated
     */
    public void setTsf2(BigDecimal tsf2) {
        this.tsf2 = tsf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.tec1
     *
     * @return the value of crc.tec1
     *
     * @mbggenerated
     */
    public BigDecimal getTec1() {
        return tec1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.tec1
     *
     * @param tec1 the value for crc.tec1
     *
     * @mbggenerated
     */
    public void setTec1(BigDecimal tec1) {
        this.tec1 = tec1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.tec2
     *
     * @return the value of crc.tec2
     *
     * @mbggenerated
     */
    public BigDecimal getTec2() {
        return tec2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.tec2
     *
     * @param tec2 the value for crc.tec2
     *
     * @mbggenerated
     */
    public void setTec2(BigDecimal tec2) {
        this.tec2 = tec2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.waterdip1
     *
     * @return the value of crc.waterdip1
     *
     * @mbggenerated
     */
    public BigDecimal getWaterdip1() {
        return waterdip1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.waterdip1
     *
     * @param waterdip1 the value for crc.waterdip1
     *
     * @mbggenerated
     */
    public void setWaterdip1(BigDecimal waterdip1) {
        this.waterdip1 = waterdip1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.waterdip2
     *
     * @return the value of crc.waterdip2
     *
     * @mbggenerated
     */
    public BigDecimal getWaterdip2() {
        return waterdip2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.waterdip2
     *
     * @param waterdip2 the value for crc.waterdip2
     *
     * @mbggenerated
     */
    public void setWaterdip2(BigDecimal waterdip2) {
        this.waterdip2 = waterdip2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.dens_obs1
     *
     * @return the value of crc.dens_obs1
     *
     * @mbggenerated
     */
    public String getDensObs1() {
        return densObs1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.dens_obs1
     *
     * @param densObs1 the value for crc.dens_obs1
     *
     * @mbggenerated
     */
    public void setDensObs1(String densObs1) {
        this.densObs1 = densObs1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.dens_obs2
     *
     * @return the value of crc.dens_obs2
     *
     * @mbggenerated
     */
    public String getDensObs2() {
        return densObs2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.dens_obs2
     *
     * @param densObs2 the value for crc.dens_obs2
     *
     * @mbggenerated
     */
    public void setDensObs2(String densObs2) {
        this.densObs2 = densObs2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.dens_15c1
     *
     * @return the value of crc.dens_15c1
     *
     * @mbggenerated
     */
    public String getDens15c1() {
        return dens15c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.dens_15c1
     *
     * @param dens15c1 the value for crc.dens_15c1
     *
     * @mbggenerated
     */
    public void setDens15c1(String dens15c1) {
        this.dens15c1 = dens15c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.dens_15c2
     *
     * @return the value of crc.dens_15c2
     *
     * @mbggenerated
     */
    public String getDens15c2() {
        return dens15c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.dens_15c2
     *
     * @param dens15c2 the value for crc.dens_15c2
     *
     * @mbggenerated
     */
    public void setDens15c2(String dens15c2) {
        this.dens15c2 = dens15c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.wvolume1
     *
     * @return the value of crc.wvolume1
     *
     * @mbggenerated
     */
    public BigDecimal getWvolume1() {
        return wvolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.wvolume1
     *
     * @param wvolume1 the value for crc.wvolume1
     *
     * @mbggenerated
     */
    public void setWvolume1(BigDecimal wvolume1) {
        this.wvolume1 = wvolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.wvolume2
     *
     * @return the value of crc.wvolume2
     *
     * @mbggenerated
     */
    public BigDecimal getWvolume2() {
        return wvolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.wvolume2
     *
     * @param wvolume2 the value for crc.wvolume2
     *
     * @mbggenerated
     */
    public void setWvolume2(BigDecimal wvolume2) {
        this.wvolume2 = wvolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.volume1
     *
     * @return the value of crc.volume1
     *
     * @mbggenerated
     */
    public BigDecimal getVolume1() {
        return volume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.volume1
     *
     * @param volume1 the value for crc.volume1
     *
     * @mbggenerated
     */
    public void setVolume1(BigDecimal volume1) {
        this.volume1 = volume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.volume2
     *
     * @return the value of crc.volume2
     *
     * @mbggenerated
     */
    public BigDecimal getVolume2() {
        return volume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.volume2
     *
     * @param volume2 the value for crc.volume2
     *
     * @mbggenerated
     */
    public void setVolume2(BigDecimal volume2) {
        this.volume2 = volume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.vcf1
     *
     * @return the value of crc.vcf1
     *
     * @mbggenerated
     */
    public BigDecimal getVcf1() {
        return vcf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.vcf1
     *
     * @param vcf1 the value for crc.vcf1
     *
     * @mbggenerated
     */
    public void setVcf1(BigDecimal vcf1) {
        this.vcf1 = vcf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.vcf2
     *
     * @return the value of crc.vcf2
     *
     * @mbggenerated
     */
    public BigDecimal getVcf2() {
        return vcf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.vcf2
     *
     * @param vcf2 the value for crc.vcf2
     *
     * @mbggenerated
     */
    public void setVcf2(BigDecimal vcf2) {
        this.vcf2 = vcf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.dcf1
     *
     * @return the value of crc.dcf1
     *
     * @mbggenerated
     */
    public BigDecimal getDcf1() {
        return dcf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.dcf1
     *
     * @param dcf1 the value for crc.dcf1
     *
     * @mbggenerated
     */
    public void setDcf1(BigDecimal dcf1) {
        this.dcf1 = dcf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.dcf2
     *
     * @return the value of crc.dcf2
     *
     * @mbggenerated
     */
    public BigDecimal getDcf2() {
        return dcf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.dcf2
     *
     * @param dcf2 the value for crc.dcf2
     *
     * @mbggenerated
     */
    public void setDcf2(BigDecimal dcf2) {
        this.dcf2 = dcf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.vol15c1
     *
     * @return the value of crc.vol15c1
     *
     * @mbggenerated
     */
    public BigDecimal getVol15c1() {
        return vol15c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.vol15c1
     *
     * @param vol15c1 the value for crc.vol15c1
     *
     * @mbggenerated
     */
    public void setVol15c1(BigDecimal vol15c1) {
        this.vol15c1 = vol15c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.vol15c2
     *
     * @return the value of crc.vol15c2
     *
     * @mbggenerated
     */
    public BigDecimal getVol15c2() {
        return vol15c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.vol15c2
     *
     * @param vol15c2 the value for crc.vol15c2
     *
     * @mbggenerated
     */
    public void setVol15c2(BigDecimal vol15c2) {
        this.vol15c2 = vol15c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.wcf1
     *
     * @return the value of crc.wcf1
     *
     * @mbggenerated
     */
    public BigDecimal getWcf1() {
        return wcf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.wcf1
     *
     * @param wcf1 the value for crc.wcf1
     *
     * @mbggenerated
     */
    public void setWcf1(BigDecimal wcf1) {
        this.wcf1 = wcf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.wcf2
     *
     * @return the value of crc.wcf2
     *
     * @mbggenerated
     */
    public BigDecimal getWcf2() {
        return wcf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.wcf2
     *
     * @param wcf2 the value for crc.wcf2
     *
     * @mbggenerated
     */
    public void setWcf2(BigDecimal wcf2) {
        this.wcf2 = wcf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.weight1
     *
     * @return the value of crc.weight1
     *
     * @mbggenerated
     */
    public BigDecimal getWeight1() {
        return weight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.weight1
     *
     * @param weight1 the value for crc.weight1
     *
     * @mbggenerated
     */
    public void setWeight1(BigDecimal weight1) {
        this.weight1 = weight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.weight2
     *
     * @return the value of crc.weight2
     *
     * @mbggenerated
     */
    public BigDecimal getWeight2() {
        return weight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.weight2
     *
     * @param weight2 the value for crc.weight2
     *
     * @mbggenerated
     */
    public void setWeight2(BigDecimal weight2) {
        this.weight2 = weight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.receive
     *
     * @return the value of crc.receive
     *
     * @mbggenerated
     */
    public BigDecimal getReceive() {
        return receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.receive
     *
     * @param receive the value for crc.receive
     *
     * @mbggenerated
     */
    public void setReceive(BigDecimal receive) {
        this.receive = receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.slop
     *
     * @return the value of crc.slop
     *
     * @mbggenerated
     */
    public BigDecimal getSlop() {
        return slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.slop
     *
     * @param slop the value for crc.slop
     *
     * @mbggenerated
     */
    public void setSlop(BigDecimal slop) {
        this.slop = slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.actual
     *
     * @return the value of crc.actual
     *
     * @mbggenerated
     */
    public BigDecimal getActual() {
        return actual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.actual
     *
     * @param actual the value for crc.actual
     *
     * @mbggenerated
     */
    public void setActual(BigDecimal actual) {
        this.actual = actual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.bill
     *
     * @return the value of crc.bill
     *
     * @mbggenerated
     */
    public BigDecimal getBill() {
        return bill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.bill
     *
     * @param bill the value for crc.bill
     *
     * @mbggenerated
     */
    public void setBill(BigDecimal bill) {
        this.bill = bill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.out_type
     *
     * @return the value of crc.out_type
     *
     * @mbggenerated
     */
    public String getOutType() {
        return outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.out_type
     *
     * @param outType the value for crc.out_type
     *
     * @mbggenerated
     */
    public void setOutType(String outType) {
        this.outType = outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.t_receive
     *
     * @return the value of crc.t_receive
     *
     * @mbggenerated
     */
    public BigDecimal gettReceive() {
        return tReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.t_receive
     *
     * @param tReceive the value for crc.t_receive
     *
     * @mbggenerated
     */
    public void settReceive(BigDecimal tReceive) {
        this.tReceive = tReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.variation
     *
     * @return the value of crc.variation
     *
     * @mbggenerated
     */
    public BigDecimal getVariation() {
        return variation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.variation
     *
     * @param variation the value for crc.variation
     *
     * @mbggenerated
     */
    public void setVariation(BigDecimal variation) {
        this.variation = variation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.v_percent
     *
     * @return the value of crc.v_percent
     *
     * @mbggenerated
     */
    public BigDecimal getvPercent() {
        return vPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.v_percent
     *
     * @param vPercent the value for crc.v_percent
     *
     * @mbggenerated
     */
    public void setvPercent(BigDecimal vPercent) {
        this.vPercent = vPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.vessel_qty
     *
     * @return the value of crc.vessel_qty
     *
     * @mbggenerated
     */
    public BigDecimal getVesselQty() {
        return vesselQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.vessel_qty
     *
     * @param vesselQty the value for crc.vessel_qty
     *
     * @mbggenerated
     */
    public void setVesselQty(BigDecimal vesselQty) {
        this.vesselQty = vesselQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.other_crc_no
     *
     * @return the value of crc.other_crc_no
     *
     * @mbggenerated
     */
    public String getOtherCrcNo() {
        return otherCrcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.other_crc_no
     *
     * @param otherCrcNo the value for crc.other_crc_no
     *
     * @mbggenerated
     */
    public void setOtherCrcNo(String otherCrcNo) {
        this.otherCrcNo = otherCrcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.remarks
     *
     * @return the value of crc.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.remarks
     *
     * @param remarks the value for crc.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.remarks1
     *
     * @return the value of crc.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.remarks1
     *
     * @param remarks1 the value for crc.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.gauge_s
     *
     * @return the value of crc.gauge_s
     *
     * @mbggenerated
     */
    public String getGaugeS() {
        return gaugeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.gauge_s
     *
     * @param gaugeS the value for crc.gauge_s
     *
     * @mbggenerated
     */
    public void setGaugeS(String gaugeS) {
        this.gaugeS = gaugeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crc.dock
     *
     * @return the value of crc.dock
     *
     * @mbggenerated
     */
    public Boolean getDock() {
        return dock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crc.dock
     *
     * @param dock the value for crc.dock
     *
     * @mbggenerated
     */
    public void setDock(Boolean dock) {
        this.dock = dock;
    }

    @Override
    public String toString() {
        return "Crc{" +
                "crcNo='" + crcNo + '\'' +
                ", d='" + d + '\'' +
                ", tank='" + tank + '\'' +
                ", cCustomer='" + cCustomer + '\'' +
                ", commodity='" + commodity + '\'' +
                ", tax=" + tax +
                ", vessel='" + vessel + '\'' +
                ", itemNo='" + itemNo + '\'' +
                ", billid=" + billid +
                ", date1=" + date1 +
                ", date2=" + date2 +
                ", gauge1=" + gauge1 +
                ", gauge2=" + gauge2 +
                ", temp1=" + temp1 +
                ", temp2=" + temp2 +
                ", tsf1=" + tsf1 +
                ", tsf2=" + tsf2 +
                ", tec1=" + tec1 +
                ", tec2=" + tec2 +
                ", waterdip1=" + waterdip1 +
                ", waterdip2=" + waterdip2 +
                ", densObs1='" + densObs1 + '\'' +
                ", densObs2='" + densObs2 + '\'' +
                ", dens15c1='" + dens15c1 + '\'' +
                ", dens15c2='" + dens15c2 + '\'' +
                ", wvolume1=" + wvolume1 +
                ", wvolume2=" + wvolume2 +
                ", volume1=" + volume1 +
                ", volume2=" + volume2 +
                ", vcf1=" + vcf1 +
                ", vcf2=" + vcf2 +
                ", dcf1=" + dcf1 +
                ", dcf2=" + dcf2 +
                ", vol15c1=" + vol15c1 +
                ", vol15c2=" + vol15c2 +
                ", wcf1=" + wcf1 +
                ", wcf2=" + wcf2 +
                ", weight1=" + weight1 +
                ", weight2=" + weight2 +
                ", receive=" + receive +
                ", slop=" + slop +
                ", actual=" + actual +
                ", bill=" + bill +
                ", outType='" + outType + '\'' +
                ", tReceive=" + tReceive +
                ", variation=" + variation +
                ", vPercent=" + vPercent +
                ", vesselQty=" + vesselQty +
                ", otherCrcNo='" + otherCrcNo + '\'' +
                ", remarks='" + remarks + '\'' +
                ", remarks1='" + remarks1 + '\'' +
                ", gaugeS='" + gaugeS + '\'' +
                ", dock=" + dock +
                '}';
    }
}