package com.smartflow.yshyerp.crc.entity;

import java.io.Serializable;
import java.util.Date;

public class Factory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.FactoryCode
     *
     * @mbggenerated
     */
    private String factorycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.CompanyId
     *
     * @mbggenerated
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.CreatorId
     *
     * @mbggenerated
     */
    private Integer creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.CreationDateTime
     *
     * @mbggenerated
     */
    private Date creationdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.EditorId
     *
     * @mbggenerated
     */
    private Integer editorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Factory.EditDateTime
     *
     * @mbggenerated
     */
    private Date editdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Factory
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.Id
     *
     * @return the value of Factory.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.Id
     *
     * @param id the value for Factory.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.FactoryCode
     *
     * @return the value of Factory.FactoryCode
     *
     * @mbggenerated
     */
    public String getFactorycode() {
        return factorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.FactoryCode
     *
     * @param factorycode the value for Factory.FactoryCode
     *
     * @mbggenerated
     */
    public void setFactorycode(String factorycode) {
        this.factorycode = factorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.Name
     *
     * @return the value of Factory.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.Name
     *
     * @param name the value for Factory.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.Description
     *
     * @return the value of Factory.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.Description
     *
     * @param description the value for Factory.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.CompanyId
     *
     * @return the value of Factory.CompanyId
     *
     * @mbggenerated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.CompanyId
     *
     * @param companyid the value for Factory.CompanyId
     *
     * @mbggenerated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.CreatorId
     *
     * @return the value of Factory.CreatorId
     *
     * @mbggenerated
     */
    public Integer getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.CreatorId
     *
     * @param creatorid the value for Factory.CreatorId
     *
     * @mbggenerated
     */
    public void setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.CreationDateTime
     *
     * @return the value of Factory.CreationDateTime
     *
     * @mbggenerated
     */
    public Date getCreationdatetime() {
        return creationdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.CreationDateTime
     *
     * @param creationdatetime the value for Factory.CreationDateTime
     *
     * @mbggenerated
     */
    public void setCreationdatetime(Date creationdatetime) {
        this.creationdatetime = creationdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.EditorId
     *
     * @return the value of Factory.EditorId
     *
     * @mbggenerated
     */
    public Integer getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.EditorId
     *
     * @param editorid the value for Factory.EditorId
     *
     * @mbggenerated
     */
    public void setEditorid(Integer editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Factory.EditDateTime
     *
     * @return the value of Factory.EditDateTime
     *
     * @mbggenerated
     */
    public Date getEditdatetime() {
        return editdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Factory.EditDateTime
     *
     * @param editdatetime the value for Factory.EditDateTime
     *
     * @mbggenerated
     */
    public void setEditdatetime(Date editdatetime) {
        this.editdatetime = editdatetime;
    }
}